export type CatalogEntry = {
  id: string;
  displayName: string;
  family: "llama" | "qwen" | "gemma" | "phi" | "mixtral";
  parameterSize: string;
  quantization: string;
  downloadSizeBytes: number;
  minVramGb: number;
  huginnValidated: boolean;
  notes: string;
};

const GB = 1024 * 1024 * 1024;

export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "llama3.2:1b",
    displayName: "Llama 3.2 1B",
    family: "llama",
    parameterSize: "1B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(1.3 * GB),
    minVramGb: 0,
    huginnValidated: true,
    notes: "Smallest model. Fast on weak hardware. Narrative quality limited.",
  },
  {
    id: "llama3.2:3b",
    displayName: "Llama 3.2 3B",
    family: "llama",
    parameterSize: "3B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(2.0 * GB),
    minVramGb: 0,
    huginnValidated: true,
    notes: "CPU fallback. Decent quality. Good baseline for low-end hosts.",
  },
  {
    id: "phi3:mini",
    displayName: "Phi 3 Mini",
    family: "phi",
    parameterSize: "3.8B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(2.3 * GB),
    minVramGb: 0,
    huginnValidated: true,
    notes: "Strong structured output for size. Good on CPU.",
  },
  {
    id: "qwen2.5:7b",
    displayName: "Qwen 2.5 7B",
    family: "qwen",
    parameterSize: "7B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(4.4 * GB),
    minVramGb: 5,
    huginnValidated: true,
    notes: "Strong JSON adherence. Good for Phase 6 LLM validation.",
  },
  {
    id: "llama3.1:8b",
    displayName: "Llama 3.1 8B",
    family: "llama",
    parameterSize: "8B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(4.7 * GB),
    minVramGb: 6,
    huginnValidated: true,
    notes: "Prior Huginn default. Broadly safe choice.",
  },
  {
    id: "gemma2:9b",
    displayName: "Gemma 2 9B",
    family: "gemma",
    parameterSize: "9B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(5.5 * GB),
    minVramGb: 7,
    huginnValidated: true,
    notes: "Strong narrative quality. Phase 8 prose reads well.",
  },
  {
    id: "qwen2.5:14b",
    displayName: "Qwen 2.5 14B",
    family: "qwen",
    parameterSize: "14B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(8.4 * GB),
    minVramGb: 10,
    huginnValidated: true,
    notes: "Sweet spot for prosumer GPUs (RTX 3080+).",
  },
  {
    id: "qwen2.5:32b",
    displayName: "Qwen 2.5 32B",
    family: "qwen",
    parameterSize: "32B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(19 * GB),
    minVramGb: 23,
    huginnValidated: false,
    notes: "Mid-range datacenter. Untested with Huginn prompts.",
  },
  {
    id: "mixtral:8x7b",
    displayName: "Mixtral 8x7B",
    family: "mixtral",
    parameterSize: "8x7B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(26 * GB),
    minVramGb: 28,
    huginnValidated: false,
    notes: "MoE architecture. Fast inference. Untested with Huginn.",
  },
  {
    id: "llama3.3:70b",
    displayName: "Llama 3.3 70B",
    family: "llama",
    parameterSize: "70B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(40 * GB),
    minVramGb: 49,
    huginnValidated: false,
    notes: "Datacenter-grade quality. Untested with Huginn.",
  },
  {
    id: "qwen2.5:72b",
    displayName: "Qwen 2.5 72B",
    family: "qwen",
    parameterSize: "72B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(41 * GB),
    minVramGb: 51,
    huginnValidated: false,
    notes: "Strong small-batch quality. Untested with Huginn.",
  },
  {
    id: "mixtral:8x22b",
    displayName: "Mixtral 8x22B",
    family: "mixtral",
    parameterSize: "8x22B",
    quantization: "Q4",
    downloadSizeBytes: Math.round(80 * GB),
    minVramGb: 88,
    huginnValidated: false,
    notes: "High-end MoE. Untested with Huginn.",
  },
  {
    id: "llama3.3:70b-fp16",
    displayName: "Llama 3.3 70B FP16",
    family: "llama",
    parameterSize: "70B",
    quantization: "FP16",
    downloadSizeBytes: Math.round(140 * GB),
    minVramGb: 149,
    huginnValidated: false,
    notes: "Full precision. Maximum quality. Untested with Huginn.",
  },
] as const;
